// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvZ3r-_cweLDFC_2iLJIpXiaaFZ4A6QqY',
    appId: '1:780904927424:web:e46d7991e4fd67bdb4dd25',
    messagingSenderId: '780904927424',
    projectId: 'andro-inc-4a906',
    authDomain: 'andro-inc-4a906.firebaseapp.com',
    storageBucket: 'andro-inc-4a906.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhxCxyt1AdcTKnU8urt8339itk489UZDM',
    appId: '1:780904927424:android:46c786c6f856d598b4dd25',
    messagingSenderId: '780904927424',
    projectId: 'andro-inc-4a906',
    storageBucket: 'andro-inc-4a906.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzSwRuZvNBFQucEsnT-i-_6T4-KSj_Als',
    appId: '1:780904927424:ios:fbede17c26f4df3ab4dd25',
    messagingSenderId: '780904927424',
    projectId: 'andro-inc-4a906',
    storageBucket: 'andro-inc-4a906.appspot.com',
    iosBundleId: 'com.example.androIncPrueba',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzSwRuZvNBFQucEsnT-i-_6T4-KSj_Als',
    appId: '1:780904927424:ios:fbede17c26f4df3ab4dd25',
    messagingSenderId: '780904927424',
    projectId: 'andro-inc-4a906',
    storageBucket: 'andro-inc-4a906.appspot.com',
    iosBundleId: 'com.example.androIncPrueba',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvZ3r-_cweLDFC_2iLJIpXiaaFZ4A6QqY',
    appId: '1:780904927424:web:ea05b8d1d0c32dc3b4dd25',
    messagingSenderId: '780904927424',
    projectId: 'andro-inc-4a906',
    authDomain: 'andro-inc-4a906.firebaseapp.com',
    storageBucket: 'andro-inc-4a906.appspot.com',
  );
}
